language: node_js
node_js:
- lts/dubnium
install:
- npm install
script:
- npm run build
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: marcoboffo.waves@gmail.com
  skip_cleanup: true
  api_key:
    secure: cKq5Ra4IrMr4Nh0JbAtRWtdrHcrW/8NmIIi9hjk/7B7WyN40nm4wj7Kx2ACiEUXHE4gaop/2g9J1jsxnSjAGp8cL1FvgI19bcxc7B4ObTK7ZFQsmD8qzTEvBFqKjhebkv6dPpLx496+VeAgsZW5c2RM2PBT923yOys5ZSFAOoo67ZEnD8LUA4fOXB/DbeJ8DAZflsG1zNdNyBzY6N/QpMroJdcg9ia8L6D0E8aUXoztRIA96z/YbbJHFQNDBGljzEz1uVMYy5h2Teq3MO9a5QsBPR4D7s9ktb0lOWIfsQk1MiRgH7hCYfIah8GEErIrjhULm6VhOuGbfGdZtERvA9eHCFUAyPy8RuTH5Ev1sCedqpQH3OemUgULvaiRj3WGqk478M1BpO8tGVkn74IWL6Y95OzdZaPdmXtrQgAuFg1np/Zfn9hbp6rvvdf+9MUxlkfHj2Jjp1XaKjYtJaQVCS/0jRJdNbptN4KRiZnHkB+4BC/EHfKh+KBBsDowPR/lTT1CFjFDVvzaI6kXMnnoLXvteNpGUeKd2ixE7DBhrj3Jf6UCS4yN0E4B4SAmyMxs6y+yOgRlNvQAhgRdlt3hg2w7oDH9izdutRFzvRtONIQX63CoSgkIW66LAccAHCretiAfUhs4FcYG7LtyvN5TsrsAihjvjAQd0HMbbaSRhe7E=
  on:
    tags: true
    repo: scaccogatto/vue-picture-master
